Basic UI integration
DerButschi/CMAutoEditor pull request #4
Opened 2023-01-02 18:45 UTC by ArchieHill

I guess the first step to having an UI. This one I quickly made allows for the csv file to be selected and the countdown modified before running the auto clicker. 

The next steps I guess would be to integrate the two data conversion files you have, maybe some auto detection of the type of file select to use the appropriate data converter? Then adjust the UI inputs to what the data convert needs from the user. 

Hopefully I've done the requirements and .spec files correctly.

2023-01-02 22:52 UTC, DerButschi requested changes
Nice optics so far. Will take a closer look and test it later.

Two things to change already:

- [x] Remove .gitignore. Other people may have (have!) other preferences
- [x] Remove change to build.spec. I'm changing that part, anyway, I'll include what you add myself.

Thanks!

2023-01-03 10:46 UTC, DerButschi requested changes
Please do some actual testing. ;-) And then address the two issues I marked. 

Generally I find the concept a little weird: People will want to click cmautoeditor, not cmautoeditorui in order to start, well, CMAutoEditor. So that's somewhat counter intuitive. Plus, I'm not convinced of the concept of importing the whole cmautoeditor script in order to just call one function. 

The question is, do you intend to have a gui for each executable (currently my the preferred solution) or one size fits it all? In the latter case, you will end up with the full depency of several scripts just to implement a gui. I think it would be way better to actually call the GUI from the actual script (so from within cmautoeditor, etc.). As I said I intend to add config files (for screen resolution, etc.) and you could even have your preferred settings or the file you are currently working on in there. You could then simply pre-feed the GUI with what is in the config file and let the user fill in stuff that may be missing. If you still what a standalone thing, consider calling the script via subprocess.Popen or similar and just setting the command line arguments via the GUI.

Last but not least: Sorry, but "Autoclicker" is an atrocious name! ;-)

2023-01-03 10:46 UTC, DerButschi commented on cmautoeditorui.py
> +    if values['filepath'] == '':
- [ ] This fails if you just close the window by clicking the "x" symbol: values then has no key "file path".
- [ ] It should be values['filepath'] != ''

2023-01-03 10:46 UTC, DerButschi commented on cmautoeditorui.py
> +        if event == sg.WIN_CLOSED or event == 'Exit':
- [ ] This doesn't work: If you select a file and then hit 'Exit' instead of 'Start Autoclicker', CMAutoEditor will still start.

2023-01-03 19:08 UTC, ArchieHill commented on cmautoeditorui.py
> +    if values['filepath'] == '':
Well this was dumb of me, I think I might have thoroughly tested it, then proceeded to make a load of changes and then not tested it again...
Should be fixed

2023-01-03 19:08 UTC, ArchieHill commented on cmautoeditorui.py
> +        if event == sg.WIN_CLOSED or event == 'Exit':
Also should be fixed

2023-01-03 19:13 UTC, ArchieHill commented
> Please do some actual testing. ;-) And then address the two issues I marked.
> 
> Generally I find the concept a little weird: People will want to click cmautoeditor, not cmautoeditorui in order to start, well, CMAutoEditor. So that's somewhat counter intuitive. Plus, I'm not convinced of the concept of importing the whole cmautoeditor script in order to just call one function.
> 
> The question is, do you intend to have a gui for each executable (currently my the preferred solution) or one size fits it all? In the latter case, you will end up with the full depency of several scripts just to implement a gui. I think it would be way better to actually call the GUI from the actual script (so from within cmautoeditor, etc.). As I said I intend to add config files (for screen resolution, etc.) and you could even have your preferred settings or the file you are currently working on in there. You could then simply pre-feed the GUI with what is in the config file and let the user fill in stuff that may be missing. If you still what a standalone thing, consider calling the script via subprocess.Popen or similar and just setting the command line arguments via the GUI.
> 
> Last but not least: Sorry, but "Autoclicker" is an atrocious name! ;-)

So I intended one gui for all the files, that way you could just load in any file and you would end up with the editor working. To avoid strong debates, I'll just comply with what you think works best. After all it's your pet project. 

I never said I was good at naming things :) I've changed auto clicker to editor and the cmautoeditorui filename doesn't matter anymore. I'll start looking into the data conversion files and adding guis to them. 

Finally I've done the code in a way so if people want to they can still input parameters into the command line and it will work as normal without the gui. I have tested this so fingers crossed it should work.

2023-01-03 20:31 UTC, DerButschi commented
> So I intended one gui for all the files, that way you could just load in any file and you would end up with the editor working. To avoid strong debates, I'll just comply with what you think works best. After all it's your pet project.
Not saying my idea is better. I thought about it for a while and just had the gut feeling that for now (while everything is in the flow) it might be better to do it that way. After all the other to scripts are just for two particular formats of input data and more may follow. *shrug*
 
> I never said I was good at naming things :) 
You think I would have called the tool "CMAutoEditor" if was good at naming? :-D
> I've changed auto clicker to editor and the cmautoeditorui filename doesn't matter anymore. I'll start looking into the data conversion files and adding guis to them.
Thanks!

> Finally I've done the code in a way so if people want to they can still input parameters into the command line and it will work as normal without the gui. I have tested this so fingers crossed it should work.
... and thanks!

Ok, code seems to do its job so I will do the merge. I'll probably change the button once more because "Start Editor" might just lead people to think that this starts CM Scenario Editor. But that's really minor. I've set up a Github Action that does the pyinstaller stuff automatically. Once that is done, I think you will have the honor of making the announcement in the forum ;-)

2023-01-03 20:32 UTC, DerButschi approved these changes

2023-01-03 20:33 UTC, merged